//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resource.BasicInput {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BasicInputRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BasicInputRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resource.BasicInput.BasicInputRes", typeof(BasicInputRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutAr.
        /// </summary>
        public static string AboutAr {
            get {
                return ResourceManager.GetString("AboutAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutEn.
        /// </summary>
        public static string AboutEn {
            get {
                return ResourceManager.GetString("AboutEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddMission.
        /// </summary>
        public static string AddMission {
            get {
                return ResourceManager.GetString("AddMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Portfolio.
        /// </summary>
        public static string AddPortfolio {
            get {
                return ResourceManager.GetString("AddPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressAr.
        /// </summary>
        public static string AddressAr {
            get {
                return ResourceManager.GetString("AddressAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressEn.
        /// </summary>
        public static string AddressEn {
            get {
                return ResourceManager.GetString("AddressEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Ar.
        /// </summary>
        public static string ContactAr {
            get {
                return ResourceManager.GetString("ContactAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact En.
        /// </summary>
        public static string ContactEn {
            get {
                return ResourceManager.GetString("ContactEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption (Ar).
        /// </summary>
        public static string DescAr {
            get {
                return ResourceManager.GetString("DescAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption2 (Ar).
        /// </summary>
        public static string DescAr2 {
            get {
                return ResourceManager.GetString("DescAr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption (En).
        /// </summary>
        public static string DescEn {
            get {
                return ResourceManager.GetString("DescEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption2 (En).
        /// </summary>
        public static string DescEn2 {
            get {
                return ResourceManager.GetString("DescEn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaceBook.
        /// </summary>
        public static string FaceBook {
            get {
                return ResourceManager.GetString("FaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Help You?.
        /// </summary>
        public static string HelpYou {
            get {
                return ResourceManager.GetString("HelpYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Can.
        /// </summary>
        public static string HowCan {
            get {
                return ResourceManager.GetString("HowCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image1.
        /// </summary>
        public static string Image1 {
            get {
                return ResourceManager.GetString("Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image2.
        /// </summary>
        public static string Image2 {
            get {
                return ResourceManager.GetString("Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image3.
        /// </summary>
        public static string Image3 {
            get {
                return ResourceManager.GetString("Image3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image4.
        /// </summary>
        public static string Image4 {
            get {
                return ResourceManager.GetString("Image4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image5.
        /// </summary>
        public static string Image5 {
            get {
                return ResourceManager.GetString("Image5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve2 Ar.
        /// </summary>
        public static string Improve2Ar {
            get {
                return ResourceManager.GetString("Improve2Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve2 En.
        /// </summary>
        public static string Improve2En {
            get {
                return ResourceManager.GetString("Improve2En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve Ar.
        /// </summary>
        public static string ImproveAr {
            get {
                return ResourceManager.GetString("ImproveAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Customer2 Ar.
        /// </summary>
        public static string ImprovedCustomer2Ar {
            get {
                return ResourceManager.GetString("ImprovedCustomer2Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Customer2 En.
        /// </summary>
        public static string ImprovedCustomer2En {
            get {
                return ResourceManager.GetString("ImprovedCustomer2En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Customer Ar.
        /// </summary>
        public static string ImprovedCustomerAr {
            get {
                return ResourceManager.GetString("ImprovedCustomerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Customer En.
        /// </summary>
        public static string ImprovedCustomerEn {
            get {
                return ResourceManager.GetString("ImprovedCustomerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve En.
        /// </summary>
        public static string ImproveEn {
            get {
                return ResourceManager.GetString("ImproveEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Main Page.
        /// </summary>
        public static string IsMainPage {
            get {
                return ResourceManager.GetString("IsMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin.
        /// </summary>
        public static string Linkedin {
            get {
                return ResourceManager.GetString("Linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo2.
        /// </summary>
        public static string Logo2 {
            get {
                return ResourceManager.GetString("Logo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Image.
        /// </summary>
        public static string MainImage {
            get {
                return ResourceManager.GetString("MainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MISSION.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissionAr.
        /// </summary>
        public static string MissionAr {
            get {
                return ResourceManager.GetString("MissionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissionAr.
        /// </summary>
        public static string MissionEn {
            get {
                return ResourceManager.GetString("MissionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameAr.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameEn.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECTS.
        /// </summary>
        public static string PROJECTS {
            get {
                return ResourceManager.GetString("PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Title Ar.
        /// </summary>
        public static string ProjectTitleAr {
            get {
                return ResourceManager.GetString("ProjectTitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Title En.
        /// </summary>
        public static string ProjectTitleEn {
            get {
                return ResourceManager.GetString("ProjectTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question ( Ar ).
        /// </summary>
        public static string QuestionAr {
            get {
                return ResourceManager.GetString("QuestionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question ( En ).
        /// </summary>
        public static string QuestionEn {
            get {
                return ResourceManager.GetString("QuestionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Image.
        /// </summary>
        public static string SubImage {
            get {
                return ResourceManager.GetString("SubImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title ( Ar ).
        /// </summary>
        public static string SubTitleAr {
            get {
                return ResourceManager.GetString("SubTitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title ( En ).
        /// </summary>
        public static string SubTitleEn {
            get {
                return ResourceManager.GetString("SubTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title 2 (Ar).
        /// </summary>
        public static string Title2Ar {
            get {
                return ResourceManager.GetString("Title2Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title 2 (En).
        /// </summary>
        public static string Title2En {
            get {
                return ResourceManager.GetString("Title2En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (Ar).
        /// </summary>
        public static string TitleAr {
            get {
                return ResourceManager.GetString("TitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (En).
        /// </summary>
        public static string TitleEn {
            get {
                return ResourceManager.GetString("TitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR VALUE.
        /// </summary>
        public static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR VALUE (Ar).
        /// </summary>
        public static string ValueAr {
            get {
                return ResourceManager.GetString("ValueAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR VALUE (En).
        /// </summary>
        public static string ValueEn {
            get {
                return ResourceManager.GetString("ValueEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR VISION.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisionAr.
        /// </summary>
        public static string VisionAr {
            get {
                return ResourceManager.GetString("VisionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisionEn.
        /// </summary>
        public static string VisionEn {
            get {
                return ResourceManager.GetString("VisionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Image.
        /// </summary>
        public static string VisionImage {
            get {
                return ResourceManager.GetString("VisionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Image2.
        /// </summary>
        public static string VisionImage2 {
            get {
                return ResourceManager.GetString("VisionImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Also Look Into The Topics Below.
        /// </summary>
        public static string YouCan {
            get {
                return ResourceManager.GetString("YouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
