//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resource.GlobalRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resource.GlobalRes.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Company.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboar Features.
        /// </summary>
        public static string AdminDashboarFeatures {
            get {
                return ResourceManager.GetString("AdminDashboarFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By Ai, Controlled By You..
        /// </summary>
        public static string Ai {
            get {
                return ResourceManager.GetString("Ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Message.
        /// </summary>
        public static string AMessage {
            get {
                return ResourceManager.GetString("AMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android And IOS.
        /// </summary>
        public static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Furnitures.
        /// </summary>
        public static string ApartmentFurnitures {
            get {
                return ResourceManager.GetString("ApartmentFurnitures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Automation {
            get {
                return ResourceManager.GetString("Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string btnApprove {
            get {
                return ResourceManager.GetString("btnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Shift.
        /// </summary>
        public static string btnCount {
            get {
                return ResourceManager.GetString("btnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string btnDetails {
            get {
                return ResourceManager.GetString("btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        public static string btnExportExcel {
            get {
                return ResourceManager.GetString("btnExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Personal Demo.
        /// </summary>
        public static string btnget {
            get {
                return ResourceManager.GetString("btnget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Excel.
        /// </summary>
        public static string btnImportExcel {
            get {
                return ResourceManager.GetString("btnImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save  And Exist.
        /// </summary>
        public static string btnSaveExist {
            get {
                return ResourceManager.GetString("btnSaveExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Your Message.
        /// </summary>
        public static string btnSendmessage {
            get {
                return ResourceManager.GetString("btnSendmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string btnShowAll {
            get {
                return ResourceManager.GetString("btnShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string ChangePasswordSuccuss {
            get {
                return ResourceManager.GetString("ChangePasswordSuccuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact To Get.
        /// </summary>
        public static string ContactToGet {
            get {
                return ResourceManager.GetString("ContactToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the current password correctly.
        /// </summary>
        public static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy To Use.
        /// </summary>
        public static string EasyToUse {
            get {
                return ResourceManager.GetString("EasyToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhancement In Growing.
        /// </summary>
        public static string EnhancementInGrowing {
            get {
                return ResourceManager.GetString("EnhancementInGrowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faqs.
        /// </summary>
        public static string Faqs {
            get {
                return ResourceManager.GetString("Faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateExcel.
        /// </summary>
        public static string GenerateExcel {
            get {
                return ResourceManager.GetString("GenerateExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneratePDF.
        /// </summary>
        public static string GeneratePDF {
            get {
                return ResourceManager.GetString("GeneratePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you contacted one of our representatives?.
        /// </summary>
        public static string Haveyoucontacted {
            get {
                return ResourceManager.GetString("Haveyoucontacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Costs.
        /// </summary>
        public static string InCosts {
            get {
                return ResourceManager.GetString("InCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Security.
        /// </summary>
        public static string InSecurity {
            get {
                return ResourceManager.GetString("InSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Success.
        /// </summary>
        public static string InSuccess {
            get {
                return ResourceManager.GetString("InSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainHeader.
        /// </summary>
        public static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Maintain.
        /// </summary>
        public static string Maintain {
            get {
                return ResourceManager.GetString("Maintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Succuss.
        /// </summary>
        public static string Messagedelete {
            get {
                return ResourceManager.GetString("Messagedelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Shure To Delete Data.
        /// </summary>
        public static string MessageDeleteDate {
            get {
                return ResourceManager.GetString("MessageDeleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been e-mailed to you.
        /// </summary>
        public static string MessageEmailSent {
            get {
                return ResourceManager.GetString("MessageEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Please try Again .
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageErrorSelectedUser.
        /// </summary>
        public static string MessageErrorSelectedUser {
            get {
                return ResourceManager.GetString("MessageErrorSelectedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Data Not Valid.
        /// </summary>
        public static string MessageExcelError {
            get {
                return ResourceManager.GetString("MessageExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Row Or More To Delete.
        /// </summary>
        public static string MessageSelectRow {
            get {
                return ResourceManager.GetString("MessageSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Succuss.
        /// </summary>
        public static string MessageSuccuss {
            get {
                return ResourceManager.GetString("MessageSuccuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Succuss.
        /// </summary>
        public static string MessageUpdate {
            get {
                return ResourceManager.GetString("MessageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Friendly.
        /// </summary>
        public static string MobileFriendly {
            get {
                return ResourceManager.GetString("MobileFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchResult.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Us.
        /// </summary>
        public static string SendUs {
            get {
                return ResourceManager.GetString("SendUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider1 Home Image.
        /// </summary>
        public static string SliderImage1 {
            get {
                return ResourceManager.GetString("SliderImage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider2 Home Image.
        /// </summary>
        public static string SliderImage2 {
            get {
                return ResourceManager.GetString("SliderImage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Image Product.
        /// </summary>
        public static string SliderImageProduct {
            get {
                return ResourceManager.GetString("SliderImageProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Us.
        /// </summary>
        public static string Us {
            get {
                return ResourceManager.GetString("Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dashboard.
        /// </summary>
        public static string UserDashboard {
            get {
                return ResourceManager.GetString("UserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dashboar Features.
        /// </summary>
        public static string UserDashboarFeatures {
            get {
                return ResourceManager.GetString("UserDashboarFeatures", resourceCulture);
            }
        }
    }
}
